package org.ethereumphone.andyclaw.memory.model

/**
 * Describes how a memory was created.
 *
 * Maps conceptually to OpenClaw's `MemorySource` ("memory" | "sessions"),
 * but extended for Android-specific use cases.
 */
enum class MemorySource {
    /** Explicitly stored by the user or agent (e.g. "remember this"). */
    MANUAL,

    /** Automatically extracted from a conversation session. */
    CONVERSATION,

    /** Generated by the system (e.g. summaries, facts, preferences). */
    SYSTEM,
}
