package org.ethereumphone.andyclaw.sessions.model

/**
 * Role of a message in a chat session transcript.
 *
 * Mirrors the roles used by LLM APIs (user, assistant, system, tool).
 */
enum class MessageRole {
    /** A message sent by the human user. */
    USER,
    /** A reply generated by the AI assistant. */
    ASSISTANT,
    /** A system-level instruction injected at the start of a session. */
    SYSTEM,
    /** The result of a tool/skill execution. */
    TOOL;

    companion object {
        /**
         * Case-insensitive lookup; returns [USER] for unknown values.
         */
        fun fromString(value: String): MessageRole {
            return entries.firstOrNull { it.name.equals(value, ignoreCase = true) } ?: USER
        }
    }
}
